import "./globals.css";

import { getLocale } from "next-intl/server";
import { Bricolage_Grotesque } from "next/font/google";

import { getLangDir } from "rtl-detect";

import { Toaster } from "@/modules/shared/components";
import { ThemeProvider, QueryClientProvider } from "@/modules/shared/providers";

import type { Metadata } from "next";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const direction = getLangDir(locale);

  return (
    <html lang={locale}>
      <body dir={direction} className={bricolage.className}>
        <ThemeProvider enableSystem attribute="class" defaultTheme="system">
          <QueryClientProvider>{children}</QueryClientProvider>
          <Toaster richColors position="top-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
