import "./globals.css";
import { Bricolage_Grotesque } from "next/font/google";
import { QueryClientProvider, ThemeProvider } from "@/modules/shared/providers";
import { Toaster } from "@/modules/shared/components";
import type { Metadata } from "next";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bricolage.className}>
        <ThemeProvider enableSystem attribute="class" defaultTheme="system">
          <QueryClientProvider>{children}</QueryClientProvider>
          <Toaster richColors position="top-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
